name: unetpedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Requests
  dio: ^5.4.3+1
  dartz: ^0.10.1

  # States
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5

  # Firebase
  # firebase_core: ^2.31.0
  # firebase_messaging: ^14.9.2

  # Regular
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  image_picker: ^1.1.1
  file_picker: ^8.0.3
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  cached_network_image: ^3.3.1
  # flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
