name: unetpedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Requests
  dio: ^5.8.0+1
  dartz: ^0.10.1

  # States
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1

  # Regular
  intl: ^0.20.2
  flutter_svg: ^2.1.0
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5
  permission_handler: ^12.0.0+1
  cached_network_image: ^3.4.1
  flutter_pdfview: ^1.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
